# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
NULL

VB_tLMFMcpp <- function(Y, M_int, S1_int, S2_int, mu_int, R_int, C_int, Lam1_int, Lam2_int, nu_int, add_IC_iter, epsELBO, maxIter, verbose, cal_eigs = FALSE) {
    .Call(`_RMFM_VB_tLMFMcpp`, Y, M_int, S1_int, S2_int, mu_int, R_int, C_int, Lam1_int, Lam2_int, nu_int, add_IC_iter, epsELBO, maxIter, verbose, cal_eigs)
}

